# John Griffith '2015'

FROM ubuntu:latest
MAINTAINER John Griffith "john.griffith8@gmail.com"

RUN apt-get update -y
RUN apt-get install -y vim git python-pip python-dev
RUN pip install paramiko
RUN pip install pika
