# John Griffith '2015'

FROM ubuntu
MAINTAINER John Griffith "john.griffith8@gmail.com"
RUN apt-get update -y
RUN apt-get install -y vim git python-dev python-pip
RUN pip install ansible
RUN pip install paramiko
RUN pip install pika
RUN pip install ansible
RUN pip install random_name
RUN pip install python-openstackclient
RUN pip install os-client-config
RUN pip install shade
